### ISSUE TITLE
Cleanup branches main vs gh-pages

### ISSUE THREAD

**Issue by durack1** [WCRP-CMIP/WGCM_Infrastructure_Panel#8]
There are inconsistencies between these branches that need to be merged. It would make sense that we collapse branches so a single branch is maintained

**Comment by matthew-mizielinski** [comment]
Currently the pages available are served via the `doc` directory of the `gh-pages` branch rather than from main.

I'm going to spend a bit of time pulling together information we have in various places and adding to this site, e.g. links to the various working documents we have, so my plan is to create a pull request from the gh-pages branch and merge it, reconfigure the website to look at that location before tweaking #9 and merging.

Once I've done that I'll branch and pull together other information to add to this site.

@martinjuckes, I think you configured much of this site last autumn -- any objections to the above?

**Comment by durack1** [comment]
@matthew-mizielinski thanks for sorting this out, I like what you propose which will update and clean things up well!

**Comment by matthew-mizielinski** [comment]
#10 pulls the changes in the gh-pages branch into the main branch and I've updated the Pages settings to point at main.

**Comment by matthew-mizielinski** [comment]
I'll close this in a couple of days if I don't hear of any issues.
